/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Notes.framework/Notes
 */

@interface NoteObject : NSManagedObject <ICSearchIndexableNote>

@property (nonatomic, retain) NSSet *attachments;
@property (nonatomic, retain) NSString *author;
@property (nonatomic, retain) NoteBodyObject *body;
@property (nonatomic, retain) NSNumber *containsCJK;
@property (nonatomic, retain) NSString *content;
@property (nonatomic, readonly) NSString *contentAsPlainText;
@property (nonatomic, retain) NSNumber *contentType;
@property (nonatomic, retain) NSDate *creationDate;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, retain) NSNumber *deletedFlag;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSString *externalContentRef;
@property (nonatomic, retain) NSNumber *externalFlags;
@property (nonatomic, retain) NSData *externalRepresentation;
@property (nonatomic, retain) NSNumber *externalSequenceNumber;
@property (nonatomic, retain) NSNumber *externalServerIntId;
@property (nonatomic) unsigned long long flags;
@property (nonatomic, readonly, retain) NSString *guid;
@property (nonatomic, readonly) BOOL hasValidServerIntId;
@property (readonly) unsigned int hash;
@property (nonatomic, retain) NSNumber *integerId;
@property (nonatomic, readonly) BOOL isBeingMarkedForDeletion;
@property (nonatomic, retain) NSNumber *isBookkeepingEntry;
@property (nonatomic, readonly) BOOL isMarkedForDeletion;
@property (nonatomic) BOOL isPlainText;
@property (nonatomic, retain) NSDate *modificationDate;
@property (nonatomic, readonly) NSURL *noteId;
@property (nonatomic) unsigned long long sequenceNumber;
@property (nonatomic, retain) NSString *serverId;
@property (nonatomic) long long serverIntId;
@property (nonatomic, retain) NoteStoreObject *store;
@property (nonatomic, retain) NSString *summary;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSString *title;

+ (BOOL)didChooseToMigrateNote:(id)arg1 context:(struct NoteContext { Class x1; id x2; id x3; id x4; id x5; unsigned int x6; BOOL x7; BOOL x8; BOOL x9; BOOL x10; id x11; /* Warning: Unrecognized filer type: '' using 'void*' */ void*x12; void*x13; void*x14; void*x15; void*x16; void*x17; void*x18; void*x19; void*x20; void*x21; void*x22; void*x23; SEL x24; void*x25; void*x26; void*x27; void*x28; void*x29; void*x30; void*x31; void*x32; void*x33; void*x34; void*x35; void*x36; void*x37; void*x38; void*x39; void*x40; void*x41; void*x42; void*x43; void*x44; void*x45; void*x46; void*x47; void*x48; void*x49; void*x50; void*x51; void*x52; void*x53; void*x54; void*x55; void*x56; void*x57; }*)arg2;
+ (id)searchIndexableObjectWithIdentifier:(id)arg1 includeDeleted:(BOOL)arg2 inNoteContext:(id)arg3;

- (BOOL)belongsToCollection:(id)arg1;
- (BOOL)containsAttachments;
- (id)content;
- (id)contentAsPlainText;
- (id)contentAsPlainTextPreservingNewlines;
- (id)contentInfoText;
- (id)externalContentRef;
- (id)externalRepresentation;
- (unsigned long long)flags;
- (BOOL)hasValidServerIntId;
- (id)identifier;
- (BOOL)ignoreInSearchIndexer;
- (BOOL)isBeingMarkedForDeletion;
- (BOOL)isHiddenFromSearch;
- (BOOL)isMarkedForDeletion;
- (BOOL)isPlainText;
- (void)markForDeletion;
- (id)noteAsPlainTextWithoutTitle;
- (id)noteId;
- (id)objectIdentifier;
- (void)releaseMemoryForIndexing;
- (id)searchDomainIdentifier;
- (id)searchIndexStringsOutHasAdditionalStrings:(BOOL*)arg1;
- (id)searchIndexableTitleUsingContentTextIfNecessary:(id)arg1;
- (BOOL)searchResultCanBeDeletedFromNoteContext;
- (unsigned int)searchResultsSection;
- (id)searchableContentKeyPaths;
- (id)searchableItemAttributeSet;
- (id)searchableItemIdentifier;
- (unsigned long long)sequenceNumber;
- (long long)serverIntId;
- (void)setContent:(id)arg1;
- (void)setExternalContentRef:(id)arg1;
- (void)setExternalRepresentation:(id)arg1;
- (void)setFlags:(unsigned long long)arg1;
- (void)setIsPlainText:(BOOL)arg1;
- (void)setSequenceNumber:(unsigned long long)arg1;
- (void)setServerIntId:(long long)arg1;
- (BOOL)shouldUpdateIndexForChangedValues:(id)arg1;
- (int)visibilityTestingType;

@end
