/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PassKit.framework/PassKit
 */

@interface PKTableViewCell : UITableViewCell {
    UIColor * _checkmarkAccessoryColor;
    UIColor * _customAccessoryColor;
    UIColor * _highlightColor;
}

@property (nonatomic, copy) UIColor *checkmarkAccessoryColor;
@property (nonatomic, copy) UIColor *customAccessoryColor;
@property (nonatomic, copy) UIColor *highlightColor;

- (id)_checkmarkImage:(BOOL)arg1;
- (id)_disclosureChevronImage:(BOOL)arg1;
- (id)checkmarkAccessoryColor;
- (id)customAccessoryColor;
- (id)highlightColor;
- (void)pk_applyAppearance:(struct _PKAppearanceSpecifier { BOOL x1; id x2; id x3; id x4; id x5; id x6; id x7; id x8; id x9; id x10; id x11; id x12; id x13; /* Warning: Unrecognized filer type: '' using 'void*' */ void*x14; void*x15; void*x16; void*x17; void*x18; void*x19; void*x20; void*x21; SEL x22; void*x23; void*x24; void*x25; void*x26; unsigned char x27; void*x28; unsigned short x29; void*x30; short x31; void*x32; void*x33; void*x34; void*x35; unsigned long x36; int x37; unsigned int x38/* : ? */; const void*x39; const void*x40; void*x41; void*x42; const int x43; void x44; void*x45; void*x46; void*x47; void*x48; const void*x49; void*x50; void*x51; void*x52; out const void*x53; short x54; void*x55; int x56; void*x57; out const void*x58; unsigned int x59; void*x60; void*x61; out const void*x62; void*x63; float x64; const void*x65; void*x66; void*x67; void*x68; out const void*x69; void*x70; int x71; void*x72; out const void*x73; unsigned int x74; void*x75; void*x76; out const void*x77; void*x78; void*x79; void*x80; void*x81; void*x82; void*x83; void*x84; SEL x85; void*x86; void*x87; void*x88; void*x89; void*x90; void*x91; void*x92; void*x93; void*x94; void*x95; void*x96; void*x97; void*x98; void*x99; void*x100; void*x101; void*x102; void*x103; void*x104; void*x105; void*x106; void*x107; void*x108; void*x109; void*x110; void*x111; void*x112; void*x113; void*x114; void*x115; void*x116; void*x117; void*x118; }*)arg1;
- (void)setCheckmarkAccessoryColor:(id)arg1;
- (void)setCustomAccessoryColor:(id)arg1;
- (void)setHighlightColor:(id)arg1;

@end
