/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MetalPerformanceShaders.framework/MetalPerformanceShaders
 */

@interface MPSCommandBufferImageCache : NSObject {
    <MTLCommandBuffer> * _cmdBuffer;
    int  _debugMode;
    <MTLDevice> * _device;
    struct CacheFrame { struct CacheFrame {} *x1; struct BufferNode {} *x2; struct TextureNode {} *x3; } * _frameList;
    struct BufferNode { struct BufferNode {} *x1; id x2; } * _freeList;
    int  _gpuType;
    BOOL  _needsRetain;
    struct TextureNode { struct TextureNode {} *x1; id x2; /* Warning: Unrecognized filer type: '' using 'void*' */ void*x3; void*x4; void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; void*x15; void*x16; void*x17; void*x18; void*x19; void*x20; void*x21; void*x22; void*x23; void*x24; void*x25; void*x26; void*x27; void*x28; void*x29; void*x30; void*x31; void*x32; void*x33; void*x34; void*x35; void*x36; void*x37; void*x38; void*x39; void*x40; void*x41; void*x42; void*x43; void*x44; void*x45; void*x46; SEL x47; void*x48; void*x49; void*x50; void*x51; void*x52; unsigned short x53; void*x54; long doublex55; void*x56; void*x57; void*x58; out in unsigned char x59; out in in void*x60; BOOL x61; void*x62; int x63; out in void*x64; void*x65; void*x66; void*x67; void*x68; void*x69; void*x70; void*x71; SEL x72; void*x73; void*x74; void*x75; void*x76; void*x77; void*x78; void*x79; void*x80; void*x81; void*x82; void*x83; void*x84; void*x85; void*x86; void*x87; void*x88; void*x89; void*x90; void*x91; void*x92; void*x93; void*x94; void*x95; void*x96; void*x97; void*x98; void*x99; void*x100; void*x101; void*x102; void*x103; void*x104; SEL x105; void*x106; } * _retainedTextures;
    struct MIAutoCache { id x1; } * _userCacheFrame;
}

@property (nonatomic, readonly) <MTLCommandBuffer> *commandBuffer;

- (id)commandBuffer;
- (void)dealloc;
- (id)debugDescription;
- (void)flushDeviceOnlyBufferCache;
- (id)initWithCommandBuffer:(id)arg1;
- (id)newTempBuffer:(unsigned long)arg1;
- (void)releaseTempBuffer:(id)arg1;
- (id)retainedTextures;

@end
