/* Generated by RuntimeBrowser
   Image: /usr/lib/system/introspection/libdispatch.dylib
 */

@interface OS_dispatch_object : OS_object <OS_dispatch_object>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (readonly) Class superclass;

- (void)_dispose;
- (void)_xref_dispose;
- (id)debugDescription;
- (id)init;

@end
