/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSKeyValueFastMutableOrderedSet2 : NSKeyValueFastMutableOrderedSet {
    NSKeyValueGetter * _valueGetter;
}

+ (struct { unsigned int x1; /* Warning: unhandled array encoding: '[4@]}' */ id x2[4]; void*x3; void*x4; void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; void*x15; void*x16; void*x17; void*x18; SEL x19; void*x20; void*x21; void*x22; void*x23; void*x24; void*x25; unsigned short x26; void*x27; short x28; void*x29; void*x30; void*x31; void*x32; unsigned long x33; int x34; unsigned int x35/* : ? */; const void*x36; const void*x37; void*x38; void*x39; const int x40; void x41; void*x42; void*x43; void*x44; void*x45; const void*x46; void*x47; void*x48; void*x49; out const void*x50; short x51; void*x52; unsigned char x53; void*x54; const void*x55; int x56; void*x57; void*x58; float x59; const void*x60; void*x61; void*x62; void*x63; out const void*x64; void*x65; unsigned char x66; void*x67; const void*x68; int x69; void*x70; void*x71; void*x72; void*x73; void*x74; void*x75; void*x76; void*x77; void*x78; void*x79; void*x80; void*x81; void*x82; void*x83; void*x84; void*x85; void*x86; void*x87; void*x88; void*x89; void*x90; }*)_proxyNonGCPoolPointer;

- (id)_nonNilOrderedSetValueWithSelector:(SEL)arg1;
- (id)_proxyInitWithContainer:(id)arg1 getter:(id)arg2;
- (void)_proxyNonGCFinalize;
- (unsigned int)count;
- (void)getObjects:(id*)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
- (unsigned int)indexOfObject:(id)arg1;
- (id)objectAtIndex:(unsigned int)arg1;
- (id)objectsAtIndexes:(id)arg1;

@end
