/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSKeyValueIvarMutableArray : NSKeyValueMutableArray {
    struct objc_ivar { } * _ivar;
}

+ (struct { unsigned int x1; /* Warning: unhandled array encoding: '[4@]}' */ id x2[4]; void*x3; void*x4; void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; void*x15; void*x16; void*x17; void*x18; SEL x19; void*x20; void*x21; void*x22; void*x23; Class x24; unsigned short x25; void*x26; void*x27; unsigned int x28; void*x29; const out double x30; void*x31; BOOL x32; void*x33; unsigned long x34; out BOOL x35; void*x36; void*x37; void*x38; unsigned char x39; out long x40; long x41; void*x42; BOOL x43; void*x44; int x45; out in oneway int x46; void*x47; void*x48; unsigned char x49; void*x50; long x51; long x52; void*x53; void*x54; void*x55; void*x56; void*x57; void*x58; void*x59; unsigned long long x60; void*x61; void*x62; void*x63; void*x64; SEL x65; void*x66; void*x67; void*x68; void*x69; void*x70; void*x71; void*x72; void*x73; void*x74; void*x75; void*x76; void*x77; void*x78; void*x79; void*x80; void*x81; void*x82; void*x83; void*x84; void*x85; void*x86; void*x87; void*x88; void*x89; void*x90; void*x91; SEL x92; void*x93; void*x94; void*x95; void*x96; void*x97; void*x98; void*x99; void*x100; unsigned short x101; void*x102; void*x103; const void*x104; double x105; unsigned long x106; int x107; unsigned int x108/* : ? */; const void*x109; const int x110; void*x111; short x112; oneway int x113; void*x114; void*x115; unsigned char x116; out in void*x117; const out long x118; long x119; void*x120; const void*x121; void*x122; void*x123; void*x124; void*x125; void*x126; void*x127; void*x128; void*x129; void*x130; void*x131; void*x132; }*)_proxyNonGCPoolPointer;

- (id)_nonNilMutableArrayValueWithSelector:(SEL)arg1;
- (id)_proxyInitWithContainer:(id)arg1 getter:(id)arg2;
- (void)_proxyNonGCFinalize;
- (void)_raiseNilValueExceptionWithSelector:(SEL)arg1;
- (void)addObject:(id)arg1;
- (unsigned int)count;
- (void)getObjects:(id*)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
- (void)insertObject:(id)arg1 atIndex:(unsigned int)arg2;
- (void)insertObjects:(id)arg1 atIndexes:(id)arg2;
- (id)objectAtIndex:(unsigned int)arg1;
- (id)objectsAtIndexes:(id)arg1;
- (void)removeLastObject;
- (void)removeObjectAtIndex:(unsigned int)arg1;
- (void)removeObjectsAtIndexes:(id)arg1;
- (void)replaceObjectAtIndex:(unsigned int)arg1 withObject:(id)arg2;
- (void)replaceObjectsAtIndexes:(id)arg1 withObjects:(id)arg2;

@end
