/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EDWarnings : NSObject {
    struct __CFArray { } * mWarnings;
}

- (void)addWarning:(struct TCTaggedMessageStructure { int x1; id x2; /* Warning: Unrecognized filer type: '' using 'void*' */ void*x3; void*x4; void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; SEL x15; void*x16; void*x17; void*x18; void*x19; unsigned char x20; void*x21; unsigned short x22; void*x23; short x24; void*x25; void*x26; void*x27; void*x28; unsigned long x29; int x30; unsigned int x31/* : ? */; const void*x32; const void*x33; void*x34; void*x35; const int x36; void x37; void*x38; void*x39; void*x40; void*x41; const void*x42; void*x43; void*x44; void*x45; out const void*x46; short x47; void*x48; int x49; void*x50; out const void*x51; unsigned int x52; void*x53; void*x54; out const void*x55; void*x56; float x57; const void*x58; void*x59; void*x60; void*x61; out const void*x62; void*x63; int x64; void*x65; out const void*x66; unsigned int x67; void*x68; void*x69; out const void*x70; void*x71; void*x72; void*x73; void*x74; void*x75; void*x76; void*x77; void*x78; void*x79; void*x80; void*x81; void*x82; void*x83; void*x84; void*x85; void*x86; void*x87; void*x88; struct x89; void*x90; void*x91; void*x92; void*x93; void*x94; char *x95; void*x96; void*x97; void*x98; void*x99; void*x100; void*x101; void*x102; char *x103; void*x104; void*x105; void*x106; void*x107; void*x108; }*)arg1;
- (void)dealloc;
- (id)init;
- (void)reportWarningsWithAssociatedObject:(id)arg1;

@end
